#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

// Fix arguments to work with class ArgVInput
$args = collect(["app-name-placeholder-to-remove", "stimpack"])->merge(
    collect($_SERVER['argv'])->splice(1)
)->toArray();

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput($args),
    new Symfony\Component\Console\Output\ConsoleOutput    
);

$kernel->terminate($input, $status);
exit($status);